name:                image-import
version:             0.1.0.0
github:              "balp/image-import"
license:             BSD3
author:              "Anders Arnholm"
maintainer:          "anders@arnholm.se"
copyright:           "2020 Anders Arnholm"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Something

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/balp/image-import#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  image-import-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image-import

tests:
  image-import-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image-import
    - HUnit
    - test-framework
    - test-framework-hunit
